# Generated by Django 4.0.4 on 2022-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_properties_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
